# Generated by Django 4.2.5 on 2023-10-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('program', models.CharField(max_length=255)),
                ('weight', models.JSONField()),
                ('bench', models.JSONField()),
                ('squat', models.JSONField()),
                ('deadlift', models.JSONField()),
                ('custom', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
